project/app/urls.py
from django.urls import path, include
from app import views

app_name = 'app'

urlpatterns = [
    path('', views.DashboardPage.as_view(), name='dashboard'),
    path('user/', views.UserPage.as_view(), name='user'),
    path('tables/', views.TablesPage.as_view(), name='tables'),
    path('message/create/', views.GetMessage.as_view(), name='create'),
    path('message/edit/<int:pk>', views.UpdateMessage.as_view(), name='edit'),
    path('message/delete/<int:pk>', views.DeleteMessage.as_view(), name='delete'),
    path('contact/',views.ContactView.as_view(), name='contact'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    # 認証
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('social_django.urls', namespace='social')),
    # アプリケーション
    path('', include('app.urls')),
]

project/templates/app/base.html
{% load staticfiles %}

<!doctype html>
<html lang="ja">

<head>
  <meta charset="utf-8"/>

  <title>Social Recruiter</title>

  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'app/assets/css/material-dashboard.css' %}" rel="stylesheet" />
  <link href="{% static 'app/assets/css/custom.css' %}" rel="stylesheet" />
  <link href="{% static 'app/assets/css/animsition.min.css' %}" rel="stylesheet" />
</head>

<body class="">
  <div class="wrapper animsition">
    <div class="sidebar" data-color="purple" data-background-color="white">
      <div class="logo">
        <a href="/" class="simple-text logo-normal">
          Social Recruiter
        </a>
      </div>

      <!-- 左のサイドバー -->
      <div class="sidebar-wrapper">
          <ul class="nav">
              <li class="nav-item" id="dashboard">
                  <a class="nav-link" href="/">
                      <i class="material-icons">dashboard</i>
                      <p>Dashboard</p>
                  </a>
              </li>
              <!--
              <li class="nav-item" id="user">
                  <a class="nav-link" href="/user">
                      <i class="material-icons">person</i>
                      <p>User Profile</p>
                  </a>
              </li>
              -->
              <li class="nav-item" id="table">
                  <a class="nav-link" href="/tables">
                      <i class="material-icons">content_paste</i>
                      <p>Table List</p>
                  </a>
              </li>
              <li class="nav-item" id="contact">
                  <a class="nav-link" href="/contact">
                      <i class="material-icons">mail</i>
                      <p>Contact</p>
                  </a>
              </li>
              <!--
              <li class="nav-item" id="create">
                  <a class="nav-link" href="/message/create">
                      <i class="material-icons">content_paste</i>
                      <p>Message</p>
                  </a>
              </li>
              -->
              <!-- your sidebar here -->
          </ul>
      </div>

    </div>


    <div class="main-panel">
      <!-- 上の部分 -->
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">{% block active_nav_name %}{% endblock %}</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
              <!-- your navbar here -->
              <li class="nav-item">
                <a class="nav-link" href="/accounts/logout">
                  <i class="material-icons">face</i> Logout
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <!-- End Navbar -->

      <!--　選択中メインコンテンツ -->
      <div class="content">
        <div class="container-fluid">
          {% block content %}
          {% endblock %}
        </div>
      </div>


      <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>
              <li>
                <a href="https://www.dip-net.co.jp/">
                  Our Company
                </a>
              </li>
              <li>
                <a href="https://creative-tim.com/presentation">
                  About Us
                </a>
              </li>
                {% comment %}
              <li>
                <a href="http://blog.creative-tim.com">
                  Blog
                </a>
              </li>
              <li>
                <a href="https://www.creative-tim.com/license">
                  Licenses
                </a>
              </li>
              {% endcomment %}
            </ul>
          </nav>
        {% comment %}
          <div class="copyright float-right">
            &copy;
            <script>
              document.write(new Date().getFullYear())
            </script>, made with <i class="material-icons">favorite</i> by
            <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
          </div>
        {% endcomment %}
        </div>
      </footer>

    </div>
  </div>

  <!--   Core JS Files   -->
  <script src="{% static 'app/assets/js/core/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'app/assets/js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'app/assets/js/core/bootstrap-material-design.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'app/assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!-- Chartist JS -->
  <script src="{% static 'app/assets/js/plugins/chartist.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'app/assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'app/assets/js/material-dashboard.js' %}" type="text/javascript"></script>

  <script src="{% static 'app/assets/js/animsition.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'app/assets/js/custom.js' %}" type="text/javascript"></script>

</body>

</html>

project/templates/app/contactForm.html
{% extends "app/base.html" %}
{% block content %}
    {% if messages %}
        <div class="alert alert-success" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}

        <form method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">
                <label>{{ field.label }}{% if field.field.required %}(※必須){% endif %}</label>
                <div>{{ field }}</div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

    <script>
        var activeElement = document.getElementById('contact');
        activeElement.classList.add('active');
    </script>

{% endblock %}

project/templates/app/form.html
{% extends "app/base.html" %}
{% block content %}
    {% if messages %}
        <div class="alert alert-success" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}

    <table class="table">
        <tr>
            <th class="text-center">メッセージ内容</th>
            <th class="text-right">操作</th>
        </tr>
        <tbody>
        {% for m in mess %}
            <tr><td>{{ m.message }}</td>
                <td class="td-actions text-right">
                    <button type="button" rel="tooltip" class="btn btn-success" onclick="location.href='{% url 'app:edit' pk=m.pk %}'">
                        <i class="material-icons">edit</i>
                    </button>
                    <button type="button" rel="tooltip" class="btn btn-danger" onclick="location.href='{% url 'app:delete' pk=m.pk %}'">
                        <i class="material-icons">close</i>
                    </button>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    {% with form as f %}
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>{{ f.message.label }}</label>
                <div>{{ f.message }}</div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    {% endwith %}

    <div class="iframe-container d-none d-lg-block">
      <iframe src="https://www.amazon.co.jp/">
        <p>Your browser does not support iframes.</p>
      </iframe>
    </div>

    <script>
        var activeElement = document.getElementById('create');
        activeElement.classList.add('active');
    </script>

{% endblock %}

project/templates/app/form_update.html
{% extends "app/base.html" %}
{% block content %}
    {% if messages %}
        <div class="alert alert-success" role="alert">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}

    {% with form as f %}
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>{{ f.message.label }}</label>
                <div>{{ f.message }}</div>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>

    {% endwith %}
    <script>
        var activeElement = document.getElementById('create');
        activeElement.classList.add('active');
    </script>

{% endblock %}

project/templates/app/list.html
<h1>Message</h1>
<ul>
    {% for article in object_list %}
        <li>{{ article.message }}</li>
    {% empty %}
        <li>No articles yet.</li>
    {% endfor %}
</ul>

project/templates/app/lp.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Social Recruiter</title>

  <!-- Custom fonts for this template -->
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- Bootstrap -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  <!-- Custom styles for this template -->
  <link href="{% static 'lp/css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav.is-fixed">
    <div class="container">
      <a class="navbar-brand" href="#top">Start Bootstrap</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fa fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="#home">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#post">Post</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#contact">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'social:begin' 'twitter' %}">SIGNUP</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{% static 'lp/img/home-bg.jpg' %}')" id='top'>
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>Social Recruiter</h1>
            <span class="subheading">Let's hire engineers by letting go</span>
          </div>
        </div>
      </div>
    </div>
  </header>


  <!-- Main Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

            <h2 class="section-heading" id='home'>Home</h2>
              <p>Never in all their history have men been able truly to conceive of the world as one: a single sphere, a globe, having the qualities of a globe, a round earth in which all the directions eventually meet, in which there is no center because every point, or none, is center — an equal earth which all men occupy as equals. The airman's earth, if free men make it, will be truly round: a globe in practice, not in theory.</p>

              <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>

              <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>


            <h2 class="section-heading" id='about'>About</h2>
              <p>Science cuts two ways, of course; its products can be used for both good and evil. But there's no turning back from science. The early warnings about technological dangers also come from science.</p>

              <p>What was most significant about the lunar voyage was not that man set foot on the Moon but that they set eye on the earth.</p>


            <h2 class="section-heading" id='post'>Post</h2>
              <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>

              <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>


            <h2 class="section-heading" id='contact'>Contact</h2>
              <p>A Chinese tale tells of some men sent to harm a young girl who, upon seeing her beauty, become her protectors rather than her violators. That's how I felt seeing the Earth for the first time. I could not help but love and cherish her.</p>

              <p>For those who have seen the Earth from space, and for the hundreds and perhaps thousands more who will, the experience most certainly changes your perspective. The things that we share in our world are far more valuable than those which divide us.</p>

          </div>
        </div>
      </div>
  </article>


  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fa fa-circle fa-stack-2x"></i>
                  <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Custom scripts for this template -->
  <script src="{% static 'lp/js/clean-blog.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>

</body>

</html>

project/templates/app/message_confirm_delete.html
{% extends 'app/base.html' %}
{% block meta_title %}削除確認{% endblock %}
{% block page_title %}削除確認{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12">

                <p>メッセージ内容：{{ object.message }} </p>
                <p>削除していいですか?</p>
                <form method="post">
                    <button class="btn btn-danger">削除する</button>
                    {% csrf_token %}
                </form>
            </div>
        </div>
    </div>
    <script>
        var activeElement = document.getElementById('create');
        activeElement.classList.add('active');
    </script>
{% endblock %}

project/templates/app/tables.html
{% extends 'app/base.html' %}
{% load app_tag %}

{% block display_nav %}Table List{% endblock %}
{% block active_nav_name %}Table List{% endblock %}


{% block content %}

    <div class="content">
    <div class="container-fluid">
    <div class="row">

    <div class="col-md-12">
        <div class="card">
            <div class="card-header card-header-primary">
                <h4 class="card-title ">
                    {{ q|default:"" }}エンジニア
                    {{ count }}人
                </h4>
                <form class="navbar-form" action="/tables" method="GET">
                    <div class="input-group no-border">
                        <input type="text" value="" class="form-control" placeholder="Search..." name="q">
                        <button type="submit" class="btn btn-white btn-round btn-just-icon">
                            <i class="material-icons">search</i>
                            <div class="ripple-container"></div>
                        </button>
                    </div>
                </form>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead class="text-primary">
                        <th style="width:20px;">
                            Index
                        </th>
                        <th style="width:25px;">
                            Screen_name
                        </th>
                        <th style="width:30px;">
                            location
                        </th>
                        <th>
                            follower
                        </th>
                        <th>
                            follow
                        </th>
                        <th>
                            description
                        </th>
                        </thead>
                        <tbody>
                        {% for item in object_list %}
                            <tr>
                                {# <td>{{item.id}}</td> #}
                                {% if page %}
                                    <td>{{ page|index:forloop.counter }}</td>
                                {% else %}
                                    <td>{{ forloop.counter }}</td>
                                {% endif %}
                                <td><a href='https://twitter.com/{{item.screen_name}}' target="_blank">{{item.screen_name}}</a></td>
                                <td>{{item.location}}</td>
                                <td>{{item.followers_count}}</td>
                                <td>{{item.friends_count}}</td>

                                <td>{{item.description}}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
    </div>

    {% if is_paginated %}
        <div class="pagination">
        <div class="previous-button" style="float: left; width: 50%;">
                    {% if page_obj.has_previous %}
                        {% if q %}
                            <a href="?page={{ page_obj.previous_page_number }}&q={{ q }}" class="btn btn-primary btn-lg" role="button" aria-disabled="true">&lt;&lt; Prev</a>
                        {% else %}
                            <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-primary btn-lg" role="button" aria-disabled="true">&lt;&lt; Prev</a>
                        {% endif %}
                    {% else %}
                        <a href="#" class="btn btn-secondary btn-lg disabled" role="button" aria-disabled="true">&lt;&lt; Prev</a>
                    {% endif %}
        </div>
        <div class="next-button" style=" width: 50%; float: right; text-align: right;">
                    {% if page_obj.has_next %}
                        {% if q %}
                            <a href="?page={{ page_obj.next_page_number }}&q={{ q }}" class="btn btn-primary btn-lg" role="button" aria-disabled="true">Next &gt;&gt;</a>
                        {% else %}
                            <a href="?page={{ page_obj.next_page_number }}" class="btn btn-primary btn-lg" role="button" aria-disabled="true">Next &gt;&gt;</a>
                        {% endif %}
                    {% else %}
                        <a href="#" class="btn btn-secondary btn-lg disabled" role="button" aria-disabled="true">Next &gt;&gt;</a>
                    {% endif %}
        </div>
        </div>
    {% endif %}
    <div style="clear: both;"></div>

    <script>
        var activeElement = document.getElementById('table');
        activeElement.classList.add('active');
    </script>
{% endblock %}

project/templates/app/template.html
{% load staticfiles %}

<!doctype html>
<html lang="ja">

<head>
  <meta charset="utf-8" />
  <title>
    Material Dashboard by Creative Tim
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'app/assets/css/material-dashboard.css' %}" rel="stylesheet" />
</head>

<body class="">
  <div class="wrapper ">
    <div class="sidebar" data-color="purple" data-background-color="white">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
      -->
      <div class="logo">
        <a href="http://www.creative-tim.com" class="simple-text logo-normal">
          Creative Tim
        </a>
      </div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item active  ">
            <a class="nav-link" href="#0">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          <!-- your sidebar here -->
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top ">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="#pablo">Dashboard</a>
            <a class="navbar-brand" href="#pablo">Message</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link" href="#pablo">
                  <i class="material-icons">notifications</i> Notifications
                </a>
              </li>
              <!-- your navbar here -->
            </ul>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      <div class="content">
        <div class="container-fluid">
          <!-- your content here -->
        </div>
      </div>
      <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>
              <li>
                <a href="https://www.creative-tim.com">
                  Creative Tim
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright float-right">
            &copy;
            <script>
              document.write(new Date().getFullYear())
            </script>, made with <i class="material-icons">favorite</i> by
            <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for a better web.
          </div>
          <!-- your footer here -->
        </div>
      </footer>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="assets/js/core/jquery.min.js" type="text/javascript"></script>
  <script src="assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="assets/js/core/bootstrap-material-design.min.js" type="text/javascript"></script>
  <script src="assets/js/plugins/perfect-scrollbar.jquery.min.js"></script>
  <!--  Google Maps Plugin    -->
  <script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_HERE"></script>
  <!-- Chartist JS -->
  <script src="assets/js/plugins/chartist.min.js"></script>
  <!--  Notifications Plugin    -->
  <script src="assets/js/plugins/bootstrap-notify.js"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="assets/js/material-dashboard.min.js?v=2.1.0" type="text/javascript"></script>
</body>

</html>

project/templates/app/user.html
{% extends 'app/base.html' %}

{% block display_nav %}User Profile{% endblock %}
{% block active_nav_name %}User Profile{% endblock %}


{% block content %}
  <div>
    <div>
      <p><b>ScreenName</b>:{{ user.access_token.screen_name }}</p>
      <p><b>UserId</b>:{{ user.access_token.user_id }}</p>
      <p><b>OAuthTokenSecret</b>:{{ user.access_token.oauth_token_secret }}</p>
      <p><b>OAuthToken</b>:{{ user.access_token.oauth_token }}</p>
      <p><b>AuthTime</b>:{{ user.extra_data.auth_time }}</p>
    </div>
  </div>

    <script>
        var activeElement = document.getElementById('user');
        activeElement.classList.add('active');
    </script>
{% endblock %}